---
title: "scClassify"
author: "Yingxin Lin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{scClassify}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(scdney)
```


```{r}
data("scClassify_example")
xin_cellTypes <- scClassify_example$xin_cellTypes
exprsMat_xin_subset <- scClassify_example$exprsMat_xin_subset
wang_cellTypes <- scClassify_example$wang_cellTypes
exprsMat_wang_subset <- scClassify_example$exprsMat_wang_subset
```


```{r}
cat("Cell type composition of Xin et al. data")
table(xin_cellTypes)
cat("Cell type composition of Wang et al. data")
table(wang_cellTypes)
```


# scClassify

## Non-ensemble scClassify

```{r}
scClassify_res <- scClassify(exprsMat_train = as.matrix(exprsMat_xin_subset),
                      cellTypes_train = xin_cellTypes,
                      exprsMat_test = list(wang = as.matrix(exprsMat_wang_subset)),
                      cellTypes_test = list(wang = wang_cellTypes),
                      tree = "HOPACH",
                      algorithm = "WKNN",
                      selectFeatures = c("limma"),
                      similarity = c("pearson"),
                      weighted_ensemble = TRUE,
                      verbose = FALSE)

```


```{r}
table(scClassify_res$testRes$wang$pearson_WKNN_limma$predRes, wang_cellTypes)
```


## Ensemble scClassify

```{r}
scClassify_res_ensemble <- scClassify(exprsMat_train = as.matrix(exprsMat_xin_subset),
                      cellTypes_train = xin_cellTypes,
                      exprsMat_test = list(wang = as.matrix(exprsMat_wang_subset)),
                      cellTypes_test = list(wang = wang_cellTypes),
                      tree = "HOPACH",
                      algorithm = "WKNN",
                      selectFeatures = c("limma"),
                      similarity = c("pearson", "spearman", "cosine"),
                      weighted_ensemble = TRUE,
                      verbose = FALSE)

```


```{r}
table(scClassify_res_ensemble$ensembleRes$wang$cellTypes, wang_cellTypes)
```

# Sample Size Calculation

For the purpose of illustration, here we similate an accuracy matrix

```{r}
set.seed(2019)
n <- c(seq(20, 1000, 10), seq(1100, 10000, 100))

accMat <- do.call(cbind, lapply(1:length(n), function(i){
  tmp_n <- rep(n[i], 50)
  y <- -2/(tmp_n^0.8) + 0.95 + rnorm(length(tmp_n), 0, 0.02)
  y
}))
```

## Fitting Learning Curve


```{r fig.width = 8, fig.height = 8}
res <- learningCurve(accMat = accMat, n, verbose = FALSE)
res$model$mean
res$plot
```

To get the sample size for future experiment given the accuracy rate

```{r}
getN(res, acc = 0.93)
```




# Session Info

```{r}
sessionInfo()
```
